name: update partner list json

on:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update Partner List JSON
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd scripts/compile-source-codes && npm install
      - run: cd scripts/compile-source-codes && npm run start
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_PARTNERS_BASE: ${{ secrets.AIRTABLE_PARTNERS_BASE }}
      - run: cd scripts/compile-source-codes && npm run test

      - name: Check if there is any change
        id: changes
        run: echo "name=changed::$(git status --porcelain | wc -l)"  >> $GITHUB_OUTPUT

      - name: Create Commits
        run: |
          git config user.name 'Sage Vouse'
          git config user.email 's.vouse@gmail.com'
          git add .
          git commit -m "automated: update partner list"

      - name: Submit Pull Request
        if: steps.changes.outputs.changed != 0
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update Partner List
          commit-message: "[update-partner-list] add new partners"
          assignees: PowerThePollsAdmin
          branch: update-partner-list
          delete-branch: true
