name: update partner list json

on:
  schedule:
    - cron: "0 0 * * *" # This runs the action every day at midnight UTC
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: cd scripts/compile-source-codes && npm install

      - name: Update Partner List JSON
        run: cd scripts/compile-source-codes && npm run start
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_PARTNERS_BASE: ${{ secrets.AIRTABLE_PARTNERS_BASE }}

      - name: Run tests
        run: cd scripts/compile-source-codes && npm run test

      - name: Check if there are changes
        id: changes
        run: echo "name=changed::$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push changes if any
        if: steps.changes.outputs.changed != '0'
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          git commit -m "automated: update partner list"
          git push origin HEAD:${{ github.ref }}
