name: update partner list json

on:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update Partner List JSON
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd scripts/compile-source-codes && npm install
      - run: cd scripts/compile-source-codes && npm run start

      - name: Check for Changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Create Commits
        if: steps.changes.outputs.changed == 1
        run: |
          git config user.name 'Billy Laing'
          git config user.email 'billy@powerthepolls.org'
          git add .
          git commit -m "automated: update partner list"

      - name: Submit Pull Request
        if: steps.changes.outputs.changed == 1
        uses: peter-evans/create-pull-request@v4
